"""Render docs/alerts_and_tracker.md from a Phase 11 alerts/tracker summary.

Same principle as every previous phase's report generator: built entirely
from reports/phase11/alerts_and_tracker_summary.json, never hand-typed --
including whether any alert fired at all, which is exactly the "avoid
unnecessary alert noise" case this phase has to render correctly, not just
the case where something is wrong.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def _alerts_section(alerts: list[dict[str, Any]]) -> list[str]:
    lines = ["## Alerts fired this run", ""]
    if not alerts:
        lines.append(
            "No alert fired this run — no signal's status changed since the previous "
            "recorded run. This is the expected, correct output when nothing has "
            "changed, not a sign the check didn't run (see \"Run history\" below for "
            "confirmation this run was recorded)."
        )
        lines.append("")
        return lines

    lines.append("| Signal | Transition | Severity | Message |\n|---|---|---|---|")
    for a in alerts:
        prev = a["previous_status"] or "(none)"
        lines.append(f"| {a['signal']} | {prev} → {a['status']} ({a['direction']}) | {a['severity']} | {a['message']} |")
    lines.append("")
    return lines


def _history_section(recent_history: list[dict[str, Any]]) -> list[str]:
    lines = ["## Run history", ""]
    if not recent_history:
        lines.append("No runs recorded yet.")
        lines.append("")
        return lines
    lines.append("| Run # | Generated at | Overall status |\n|---|---|---|")
    for r in recent_history:
        lines.append(f"| {r['run_seq']} | {r['generated_at']} | {r['overall_status']} |")
    lines.append("")
    return lines


def _tracker_section(open_items: list[dict[str, Any]]) -> list[str]:
    lines = ["## Discrepancy tracker — open items", ""]
    lines.append(
        "Two sources feed this tracker: Phase 02's unexplained missing-calendar-date "
        "gaps, and Phase 09's forecast discrepancies whose root-cause investigation came "
        "back \"cause unknown from available evidence.\" An item stays open across runs "
        "until either it stops recurring or a future phase resolves it — it is never "
        "silently dropped."
    )
    lines.append("")
    if not open_items:
        lines.append("No open tracker items on this run.")
        lines.append("")
        return lines

    lines.append("| Category | Severity | Description | First seen | Times seen |\n|---|---|---|---|---|")
    for item in open_items:
        lines.append(
            f"| {item['category']} | {item['severity']} | {item['description']} | "
            f"{item['first_seen_at']} | {item['times_seen']} |"
        )
    lines.append("")
    return lines


def render_alerts_report(summary: dict[str, Any], dataset_display_name: str) -> str:
    generated_at = datetime.now(timezone.utc).isoformat()
    lines: list[str] = []

    lines.append(f"# Alerts & Discrepancy Tracker — {dataset_display_name}")
    lines.append("")
    lines.append(
        "> Generated by `demandflow.reporting.generate_alerts_report` from "
        f"`reports/phase11/alerts_and_tracker_summary.json` at `{generated_at}`. Do not "
        "hand-edit — re-run the Phase 11 check and regenerate instead."
    )
    lines.append("")

    lines.append("## Scope")
    lines.append("")
    lines.append(
        "This phase has two halves. **Alerts** compare this run's Phase 10 monitoring "
        "snapshot against the previous run persisted in `monitoring_history`, firing only "
        "on a status *transition* for a signal — an unchanged status, however long it "
        "persists, never re-fires, which is the phase objective's \"avoid unnecessary "
        "alert noise\" requirement satisfied by construction, not by a suppression rule "
        "layered on top. **The discrepancy tracker** logs items that need follow-up a "
        "person, not a threshold, has to resolve: unexplained calendar gaps (Phase 02) "
        "and forecast discrepancies Phase 09 could not explain from available evidence."
    )
    lines.append("")
    lines.append(
        f"Run #{summary.get('run_seq', 'n/a')}, champion model at check time: "
        f"**{summary.get('champion_model', 'n/a')}**, overall monitoring status: "
        f"**{summary.get('overall_status', 'n/a')}**."
    )
    lines.append("")

    lines.extend(_alerts_section(summary.get("alerts", [])))
    lines.extend(_history_section(summary.get("recent_history", [])))
    lines.extend(_tracker_section(summary.get("open_tracker_items", [])))

    lines.append("## Limitations")
    lines.append("")
    lines.append(
        "- Validated end-to-end only against the small committed synthetic fixture "
        "(tests/fixtures/favorita_sample/) in this sandbox, which has no Kaggle network "
        "access — not against the real Favorita dataset.\n"
        "- The calendar-gap tracker items come from Phase 02's `missing_dates_sample`, "
        "which is truncated to at most 20 dates — a dataset with more gaps than that "
        "would only have a sample logged here, not the complete list.\n"
        "- The known-non-trading-day list (currently just December 25) is a `[DECISION]` "
        "from Phase 00's public-documentation research on this dataset, not something "
        "derived from the data itself — a real gap the list doesn't recognize is logged "
        "as open, which is the conservative (never-silently-resolve) direction to err in.\n"
        "- This phase does not send a notification anywhere (email, Slack, etc.) — it "
        "produces a structured alert record and a persisted tracker; wiring either to an "
        "actual notification channel is out of this phase's scope (no such channel is "
        "part of this project's architecture)."
    )
    lines.append("")

    return "\n".join(lines)


def generate_and_write(summary_path: Path, out_path: Path, dataset_display_name: str) -> Path:
    summary = json.loads(summary_path.read_text(encoding="utf-8"))
    content = render_alerts_report(summary, dataset_display_name)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    return out_path


def _main() -> None:
    from demandflow.config import load_config

    cfg = load_config()
    summary_path = cfg.paths.reports_dir / "phase11" / "alerts_and_tracker_summary.json"
    if not summary_path.exists():
        raise FileNotFoundError(
            f"Expected {summary_path} to exist. Run demandflow.alerts.run_alerts first."
        )
    out_path = Path("docs") / "alerts_and_tracker.md"
    generate_and_write(summary_path, out_path, cfg.dataset.display_name)
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    _main()
