"""Render docs/ml_forecasting.md from a Phase 07 ML backtest summary.

Same principle as every previous phase's report generator: built from
reports/phase07/ml_summary.json, never hand-typed -- including whether the
model even trained (small-data runs may not clear MIN_TRAINING_ROWS) and
the win/lose conclusion, computed from the real numbers.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

MODEL_LABELS = {"naive": "Naive", "seasonal_naive": "Seasonal Naive", "sba": "SBA", "lightgbm": "LightGBM"}
COMPARISON_MODELS = ["naive", "seasonal_naive", "sba"]


def _num(value: float | None, digits: int = 3) -> str:
    return "n/a" if value is None else f"{value:,.{digits}f}"


def _label(model: str) -> str:
    return MODEL_LABELS.get(model, model)


def render_ml_report(summary: dict[str, Any], dataset_display_name: str, horizon_days: int) -> str:
    generated_at = datetime.now(timezone.utc).isoformat()
    lines: list[str] = []

    lines.append(f"# Machine Learning Forecasting — {dataset_display_name}")
    lines.append("")
    lines.append(
        f"> Generated by `demandflow.reporting.generate_ml_report` from "
        f"`reports/phase07/ml_summary.json` at `{generated_at}`. Do not hand-edit — "
        "re-run the Phase 07 backtest and regenerate instead."
    )
    lines.append("")
    lines.append(
        "**JD bonus item, not a mandatory requirement** (CLAUDE.md §5). Attempted here because "
        "a *global* model — one model fit across every hub × SKU series pooled together, not one "
        "per series — can learn shared cross-sectional patterns even from a short per-series "
        "history, which is the specific advantage ML brings for panel retail data (established "
        "practice, e.g. the M5 competition's top solutions). See docs/phase_reports/phase07.md "
        "for the full justification."
    )
    lines.append("")

    lines.append("## Train/holdout split")
    lines.append("")
    lines.append(
        f"As-of dates used: {', '.join(summary.get('as_of_dates_used', []))}. Holdout as-of date: "
        f"`{summary.get('holdout_as_of_date')}`. Horizon: {horizon_days} days."
    )
    lines.append("")
    lines.append(
        f"- Training rows: {summary.get('training_rows', 0)} "
        f"(every scorable example whose **target date** falls on or before the holdout as-of date — "
        "not just examples from an earlier as-of date; see docs/phase_reports/phase07.md for why "
        "that distinction is the one that actually prevents label leakage here)"
    )
    lines.append(f"- Holdout rows: {summary.get('holdout_rows', 0)} ({summary.get('holdout_scored_rows', 0)} scorable)")
    lines.append("")

    if not summary.get("model_trained"):
        lines.append("## Result: model not trained")
        lines.append("")
        lines.append(
            f"Training rows ({summary.get('training_rows', 0)}) fell below the minimum "
            f"({summary.get('min_training_rows_required')}) needed to fit a global model "
            "meaningfully. No LightGBM forecast was produced or evaluated on this run — this is "
            "reported as \"not evaluable\", not treated as a loss for the model."
        )
        lines.append("")
        return "\n".join(lines)

    lines.append("## Holdout comparison")
    lines.append("")
    lines.append("| Model | n | WAPE | MAE | Bias |\n|---|---|---|---|---|")
    by_model = summary.get("holdout_by_model", {})
    for model in COMPARISON_MODELS + ["lightgbm"]:
        m = by_model.get(model)
        if m:
            lines.append(f"| {_label(model)} | {m['n']} | {_num(m['wape'])} | {_num(m['mae'])} | {_num(m['forecast_bias'])} |")
    lines.append("")

    winner = summary.get("lower_wape_model")
    ml_metrics = by_model.get("lightgbm")
    best_comparison_wape = min(
        (by_model[m]["wape"] for m in COMPARISON_MODELS if m in by_model and by_model[m]["wape"] is not None),
        default=None,
    )
    lines.append(f"**Lowest WAPE on this holdout: {_label(winner) if winner else 'n/a'}.**")
    lines.append("")
    if ml_metrics and ml_metrics["wape"] is not None and best_comparison_wape is not None:
        if ml_metrics["wape"] < best_comparison_wape:
            lines.append(
                f"LightGBM (WAPE {_num(ml_metrics['wape'])}) is associated with lower error than "
                f"the best non-ML model on this holdout (WAPE {_num(best_comparison_wape)}). "
                f"This is one held-out split of {summary.get('holdout_scored_rows', 0)} scorable "
                "rows on a small development-scope fixture — encouraging, not conclusive; see "
                "docs/phase_reports/phase07.md for how much weight this result can honestly bear."
            )
        else:
            lines.append(
                f"LightGBM (WAPE {_num(ml_metrics['wape'])}) did **not** improve on the best "
                f"non-ML model on this holdout (WAPE {_num(best_comparison_wape)})."
            )
    lines.append("")

    importance = summary.get("feature_importance")
    if importance:
        lines.append("## Feature importance (LightGBM gain-based split count)")
        lines.append("")
        lines.append("| Feature | Importance |\n|---|---|")
        for feat, score in list(importance.items())[:10]:
            lines.append(f"| `{feat}` | {score} |")
        lines.append("")

    return "\n".join(lines)


def generate_and_write(summary_path: Path, out_path: Path, dataset_display_name: str, horizon_days: int) -> Path:
    summary = json.loads(summary_path.read_text(encoding="utf-8"))
    content = render_ml_report(summary, dataset_display_name, horizon_days)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    return out_path


def _main() -> None:
    from demandflow.config import load_config

    cfg = load_config()
    summary_path = cfg.paths.reports_dir / "phase07" / "ml_summary.json"
    if not summary_path.exists():
        raise FileNotFoundError(
            f"Expected {summary_path} to exist. Run demandflow.forecasting.run_ml_backtest first."
        )
    out_path = Path("docs") / "ml_forecasting.md"
    generate_and_write(summary_path, out_path, cfg.dataset.display_name, cfg.forecasting.horizon_days)
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    _main()
