"""Render docs/statistical_models.md from a Phase 06 backtest summary.

Same principle as every previous phase's report generator: built from
reports/phase06/statistical_summary.json, never hand-typed -- including the
"did Croston-family actually help" conclusion, which is computed from
whatever the real numbers say, not asserted.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

MODEL_LABELS = {
    "naive": "Naive", "seasonal_naive": "Seasonal Naive",
    "ses": "SES", "croston": "Croston", "sba": "SBA",
}
BASELINE_MODELS = ["naive", "seasonal_naive"]
STATISTICAL_MODELS = ["ses", "croston", "sba"]
CROSTON_FAMILY = ["croston", "sba"]


def _num(value: float | None, digits: int = 3) -> str:
    return "n/a" if value is None else f"{value:,.{digits}f}"


def _label(model: str) -> str:
    return MODEL_LABELS.get(model, model)


def _metrics_row(model: str, metrics: dict[str, Any]) -> str:
    return (
        f"| {_label(model)} | {metrics['n']} | {_num(metrics['wape'])} | {_num(metrics['mae'])} | "
        f"{_num(metrics['forecast_bias'])} |"
    )


def _best_model(by_model: dict[str, dict[str, Any]], candidates: list[str]) -> tuple[str | None, float | None]:
    wapes = {m: by_model[m]["wape"] for m in candidates if m in by_model and by_model[m]["wape"] is not None}
    if not wapes:
        return None, None
    best = min(wapes, key=wapes.get)
    return best, wapes[best]


def render_statistical_models_report(
    summary: dict[str, Any],
    dataset_display_name: str,
    horizon_days: int,
    season_length_days: int,
) -> str:
    generated_at = datetime.now(timezone.utc).isoformat()
    lines: list[str] = []

    lines.append(f"# Statistical Models — {dataset_display_name}")
    lines.append("")
    lines.append(
        f"> Generated by `demandflow.reporting.generate_statistical_models_report` from "
        f"`reports/phase06/statistical_summary.json` at `{generated_at}`. Do not hand-edit — "
        "re-run the Phase 06 backtest and regenerate instead."
    )
    lines.append("")

    lines.append("## Why statistical forecasting was attempted here")
    lines.append("")
    lines.append(
        "Phase 06's objective is conditional: implement statistical forecasting only if "
        "justified by the data and Phase 05's baseline results. Phase 04's SKU analysis "
        "classified most development-scope items as intermittent or lumpy (many zero-demand "
        "days). Phase 05's baselines showed WAPE at or above 1.0 on these series. Croston's "
        "method and its bias-corrected variant SBA exist specifically for intermittent demand "
        "— they smooth demand *size* and *inter-demand interval* separately, rather than "
        "smoothing the mostly-zero raw series the way Simple Exponential Smoothing (SES) or "
        "the earlier baselines effectively do. SES is included as the concrete comparison "
        "point for that failure mode, not because it was expected to win."
    )
    lines.append("")
    lines.append(
        f"Grain: hub × SKU × day. Horizon: {horizon_days} days. Season length: "
        f"{season_length_days} days. All five models share the exact same as-of-date "
        "schedule and leakage-safe backtest loop as Phase 05 — `[DECISION]` parameters, "
        "not JD requirements (see docs/phase_reports/phase06.md)."
    )
    lines.append("")

    lines.append("## Overall comparison")
    lines.append("")
    lines.append(
        f"As-of dates used: {', '.join(summary.get('as_of_dates_used', []))} "
        f"({summary.get('total_scored_records', 0)} of {summary.get('total_records', 0)} "
        "forecast rows were scorable)"
    )
    lines.append("")
    lines.append("| Model | n | WAPE | MAE | Bias |\n|---|---|---|---|---|")
    overall = summary.get("overall_by_model", {})
    for model in BASELINE_MODELS + STATISTICAL_MODELS:
        if model in overall:
            lines.append(_metrics_row(model, overall[model]))
    lines.append("")

    overall_winner = summary.get("lower_wape_model")
    baseline_best, baseline_wape = _best_model(overall, BASELINE_MODELS)
    croston_best, croston_wape = _best_model(overall, CROSTON_FAMILY)
    lines.append(f"**Lowest overall WAPE: {_label(overall_winner) if overall_winner else 'n/a'}.**")
    lines.append("")
    if croston_wape is not None and baseline_wape is not None:
        if croston_wape < baseline_wape:
            lines.append(
                f"The Croston family's best result ({_label(croston_best)}, WAPE {_num(croston_wape)}) "
                f"is **associated with lower error than** the best baseline "
                f"({_label(baseline_best)}, WAPE {_num(baseline_wape)}) overall, "
                "consistent with the justification above."
            )
        else:
            lines.append(
                f"On this run, the Croston family's best result ({_label(croston_best)}, WAPE "
                f"{_num(croston_wape)}) did **not** outperform the best baseline "
                f"({_label(baseline_best)}, WAPE {_num(baseline_wape)}). This does not by itself "
                "invalidate the justification for trying it — Croston-family methods need a "
                "reasonable number of nonzero-demand occurrences per series to let their size/"
                "interval smoothing converge; on a short history, few nonzero observations "
                "mean the estimate stays close to its initial value and offers little advantage "
                "over simpler methods. See the by-intermittency-class breakdown and "
                "docs/phase_reports/phase06.md for the full, honest read of this result."
            )
    lines.append("")

    lines.append("## By intermittency class (Phase 04 classification)")
    lines.append("")
    lines.append(
        "The direct test of this phase's justification: does the Croston family do "
        "relatively better, specifically on the intermittent/lumpy items it targets, "
        "than on other segments?"
    )
    lines.append("")
    by_segment = summary.get("by_intermittency_class", {})
    for segment in sorted(by_segment):
        by_model = by_segment[segment]
        lines.append(f"### {segment}")
        lines.append("")
        lines.append("| Model | n | WAPE | MAE | Bias |\n|---|---|---|---|---|")
        for model in BASELINE_MODELS + STATISTICAL_MODELS:
            if model in by_model:
                lines.append(_metrics_row(model, by_model[model]))
        seg_baseline_best, seg_baseline_wape = _best_model(by_model, BASELINE_MODELS)
        seg_croston_best, seg_croston_wape = _best_model(by_model, CROSTON_FAMILY)
        lines.append("")
        if seg_croston_wape is None or seg_baseline_wape is None:
            lines.append("_Not enough scored records in this segment to compare._")
        elif seg_croston_wape < seg_baseline_wape:
            lines.append(
                f"In this segment, {_label(seg_croston_best)} (WAPE {_num(seg_croston_wape)}) is "
                f"associated with lower error than {_label(seg_baseline_best)} "
                f"(WAPE {_num(seg_baseline_wape)})."
            )
        else:
            lines.append(
                f"In this segment, {_label(seg_baseline_best)} (WAPE {_num(seg_baseline_wape)}) "
                f"still shows lower error than {_label(seg_croston_best)} "
                f"(WAPE {_num(seg_croston_wape)})."
            )
        lines.append("")

    lines.append("## Final holdout (most recent as-of date)")
    lines.append("")
    holdout = summary.get("final_holdout") or {}
    if holdout:
        lines.append(f"As-of date: `{holdout.get('as_of_date')}`")
        lines.append("")
        lines.append("| Model | n | WAPE | MAE | Bias |\n|---|---|---|---|---|")
        for model in BASELINE_MODELS + STATISTICAL_MODELS:
            metrics = holdout.get("by_model", {}).get(model)
            if metrics:
                lines.append(_metrics_row(model, metrics))
    else:
        lines.append("No scored as-of date available.")
    lines.append("")

    return "\n".join(lines)


def generate_and_write(
    summary_path: Path, out_path: Path, dataset_display_name: str, horizon_days: int, season_length_days: int
) -> Path:
    summary = json.loads(summary_path.read_text(encoding="utf-8"))
    content = render_statistical_models_report(summary, dataset_display_name, horizon_days, season_length_days)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    return out_path


def _main() -> None:
    from demandflow.config import load_config

    cfg = load_config()
    summary_path = cfg.paths.reports_dir / "phase06" / "statistical_summary.json"
    if not summary_path.exists():
        raise FileNotFoundError(
            f"Expected {summary_path} to exist. Run demandflow.forecasting.run_statistical_backtest first."
        )
    out_path = Path("docs") / "statistical_models.md"
    generate_and_write(summary_path, out_path, cfg.dataset.display_name, cfg.forecasting.horizon_days, cfg.forecasting.season_length_days)
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    _main()
