"""Render docs/eda_findings.md from a Phase 04 EDA summary.

Same principle as every previous phase's report generator: built from
reports/phase04/eda_summary.json (produced by demandflow.analysis.eda),
never hand-typed, and only ever written from a real run's numbers -- the
Findings section here draws conclusions using the evidence-based language
CLAUDE.md Section 13 requires ("associated with", "consistent with",
"requires further investigation"), never asserted causation.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def _pct(value: float | None) -> str:
    return "n/a" if value is None else f"{value * 100:+.1f}%"


def _num(value: float | None, digits: int = 2) -> str:
    return "n/a" if value is None else f"{value:,.{digits}f}"


def render_eda_report(
    summary: dict[str, Any], dataset_display_name: str, chart_paths: dict[str, str] | None = None
) -> str:
    chart_paths = chart_paths or {}
    generated_at = datetime.now(timezone.utc).isoformat()
    lines: list[str] = []

    lines.append(f"# Exploratory Demand Analysis — {dataset_display_name}")
    lines.append("")
    lines.append(
        f"> Generated by `demandflow.reporting.generate_eda_report` from "
        f"`reports/phase04/eda_summary.json` at `{generated_at}`. Do not hand-edit — "
        "re-run the Phase 04 analysis and regenerate instead."
    )
    lines.append("")
    lines.append(
        "Scope: the controlled development scope (ADR 0001 §2), not the full "
        "catalog — see the dataset card. Findings below use evidence-based "
        "language (CLAUDE.md §13): an association is never presented as a "
        "proven cause."
    )
    lines.append("")

    # --- SKU ---
    lines.append("## SKUs: velocity, ABC classification, intermittency")
    lines.append("")
    lines.append(
        "| Item | Total units | ABC class | ADI | CV² | Intermittency |"
        "\n|---|---|---|---|---|---|"
    )
    for r in summary.get("sku", []):
        lines.append(
            f"| {r['item_nbr']} | {_num(r['total_unit_sales'])} | {r['abc_class']} | "
            f"{_num(r.get('adi'))} | {_num(r.get('cv_squared'))} | {r['intermittency_class']} |"
        )
    lines.append("")
    lines.append(
        "ABC class is cumulative share of development-scope volume (A ≤80%, "
        "B ≤95%, C beyond). Intermittency class follows the conventional "
        "Syntetos-Boylan-Croston thresholds (ADI≥1.32, CV²≥0.49) — "
        "`[DECISION]`, not a JD figure; relevant to Phase 05+'s method choice "
        "for these series."
    )
    lines.append("")

    # --- Hubs ---
    lines.append("## Hubs (stores)")
    lines.append("")
    lines.append("| Store | City | State | Type | Cluster | Total units | Distinct items |\n|---|---|---|---|---|---|---|")
    for r in summary.get("hubs", []):
        lines.append(
            f"| {r['store_nbr']} | {r['city']} | {r['state']} | {r['store_type']} | "
            f"{r['cluster']} | {_num(r['total_unit_sales'])} | {r['distinct_items_sold']} |"
        )
    lines.append("")

    # --- Categories ---
    lines.append("## Categories (family)")
    lines.append("")
    lines.append("| Family | Perishable | Total units | Distinct items | Avg per row |\n|---|---|---|---|---|")
    for r in summary.get("categories", []):
        lines.append(
            f"| {r['family']} | {'Yes' if r['perishable'] else 'No'} | "
            f"{_num(r['total_unit_sales'])} | {r['distinct_items']} | {_num(r['avg_unit_sales_per_row'])} |"
        )
    lines.append("")

    # --- Campaigns (promotion) ---
    lines.append("## Campaigns (promotion effect)")
    lines.append("")
    promo = summary.get("promotion_effect", {})
    for r in promo.get("by_promotion_status", []):
        label = "Promoted" if r["onpromotion"] else "Not promoted"
        lines.append(f"- **{label}**: n={r['n']}, avg unit sales={_num(r['avg_unit_sales'])}")
    lines.append(
        f"- Uplift (promoted vs. not): {_pct(promo.get('uplift_pct_promoted_vs_not'))} "
        f"(excludes {promo.get('rows_excluded_unknown_promotion', 0)} rows with unknown "
        f"promotion status and {promo.get('rows_excluded_returns', 0)} return rows)"
    )
    if chart_paths.get("promotion_uplift"):
        lines.append(f"\n![Promotion uplift]({chart_paths['promotion_uplift']})")
    lines.append("")

    # --- Pricing (explicit absence) ---
    lines.append("## Pricing")
    lines.append("")
    pricing = summary.get("pricing", {})
    lines.append(f"**Not analyzed.** {pricing.get('reason', '')}")
    lines.append("")

    # --- Seasonal events ---
    lines.append("## Seasonal events")
    lines.append("")
    seasonal = summary.get("seasonal_events", {})
    lines.append("### Holiday effect")
    lines.append("")
    for r in seasonal.get("holiday_effect", []):
        label = "Holiday" if r["is_holiday"] else "Non-holiday"
        lines.append(f"- **{label}**: n={r['n']}, avg unit sales={_num(r['avg_unit_sales'])}")
    if chart_paths.get("holiday_effect"):
        lines.append(f"\n![Holiday effect]({chart_paths['holiday_effect']})")
    lines.append("")
    lines.append("### Day-of-week")
    lines.append("")
    day_names = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]
    lines.append("| Day | n | Avg unit sales |\n|---|---|---|")
    for r in seasonal.get("day_of_week", []):
        lines.append(f"| {day_names[r['day_of_week']]} | {r['n']} | {_num(r['avg_unit_sales'])} |")
    if chart_paths.get("day_of_week"):
        lines.append(f"\n![Day of week]({chart_paths['day_of_week']})")
    lines.append("")
    lines.append("### Payday effect")
    lines.append("")
    for r in seasonal.get("payday_effect", []):
        label = "Payday" if r["is_payday"] else "Non-payday"
        lines.append(f"- **{label}**: n={r['n']}, avg unit sales={_num(r['avg_unit_sales'])}")
    lines.append("")

    # --- Trend ---
    lines.append("## Trend")
    lines.append("")
    trend = summary.get("trend", {})
    lines.append(
        f"- OLS slope: {_num(trend.get('ols_slope_per_day'), 3)} units/day "
        f"(direction: **{trend.get('trend_direction')}**), rolling window: "
        f"{trend.get('rolling_window_used')} days"
    )
    if chart_paths.get("daily_trend"):
        lines.append(f"\n![Daily trend]({chart_paths['daily_trend']})")
    lines.append("")

    # --- Outliers / anomalies with context ---
    lines.append("## Outliers and demand anomalies, with business context")
    lines.append("")
    lines.append("### DQ-flagged points (returns, extreme values), cross-referenced")
    lines.append("")
    ctx = summary.get("extreme_value_context", [])
    if ctx:
        lines.append(
            "| Date | Store | Item | Units | Return | Extreme | Promoted | Holiday |"
            "\n|---|---|---|---|---|---|---|---|"
        )
        for r in ctx:
            lines.append(
                f"| {r['date']} | {r['store_nbr']} | {r['item_nbr']} | {_num(r['unit_sales'])} | "
                f"{r['is_return']} | {r['is_extreme_value']} | {r['onpromotion']} | {r['is_holiday']} |"
            )
    else:
        lines.append("None flagged in the development scope.")
    lines.append("")
    lines.append(
        "Points not coinciding with a promotion or holiday are **not** thereby "
        "concluded to be errors — only that no explanation from the available "
        "seasonal/campaign context was found; each is a candidate for the "
        "Phase 09 RCA workflow, not a resolved finding here."
    )
    lines.append("")
    lines.append("### Network-wide anomalies (day-level)")
    lines.append("")
    anomalies = summary.get("network_anomalies", [])
    if anomalies:
        lines.append("| Date | Total units | Z-score |\n|---|---|---|")
        for a in anomalies:
            lines.append(f"| {a['date']} | {_num(a['total_unit_sales'])} | {_num(a['z_score'])} |")
    else:
        lines.append("None flagged at the current threshold.")
    lines.append("")

    return "\n".join(lines)


def generate_and_write(
    summary_path: Path,
    out_path: Path,
    dataset_display_name: str,
    chart_paths: dict[str, str] | None = None,
) -> Path:
    summary = json.loads(summary_path.read_text(encoding="utf-8"))
    content = render_eda_report(summary, dataset_display_name, chart_paths)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    return out_path


def _main() -> None:
    from demandflow.config import load_config

    cfg = load_config()
    summary_path = cfg.paths.reports_dir / "phase04" / "eda_summary.json"
    if not summary_path.exists():
        raise FileNotFoundError(
            f"Expected {summary_path} to exist. Run demandflow.analysis.eda first."
        )
    figures_dir = cfg.paths.reports_dir / "phase04" / "figures"
    chart_paths = None
    if figures_dir.exists():
        # docs/eda_findings.md is one level below the repo root, same as
        # reports/ -- so the image path is one level up, then into reports/.
        chart_paths = {
            p.stem: str(Path("..") / "reports" / "phase04" / "figures" / p.name)
            for p in figures_dir.glob("*.png")
        }
    out_path = Path("docs") / "eda_findings.md"
    generate_and_write(summary_path, out_path, cfg.dataset.display_name, chart_paths)
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    _main()
