"""Render docs/data_quality/dq_report.md from Phase 02 DQ findings.

[DECISION] Same principle as generate_dataset_card.py: generated from
reports/phase02/dq_findings.json, never hand-typed, so every number traces
back to a specific rule run rather than being retyped from memory.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

_SEVERITY_ORDER = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO", "PASS"]


def _fmt(value: Any) -> str:
    if isinstance(value, float):
        return f"{value:,.4f}"
    if isinstance(value, dict):
        return "; ".join(f"{k}={v}" for k, v in value.items())
    if isinstance(value, list):
        return ", ".join(str(v) for v in value) if value else "(none)"
    return str(value)


def render_dq_report(findings: list[dict[str, Any]], dataset_display_name: str) -> str:
    generated_at = datetime.now(timezone.utc).isoformat()
    by_severity: dict[str, int] = {s: 0 for s in _SEVERITY_ORDER}
    for f in findings:
        by_severity[f["severity"]] = by_severity.get(f["severity"], 0) + 1

    lines: list[str] = []
    lines.append(f"# Data Quality Report — {dataset_display_name}")
    lines.append("")
    lines.append(
        f"> Generated by `demandflow.reporting.generate_dq_report` from "
        f"`reports/phase02/dq_findings.json` at `{generated_at}`. Do not hand-edit — "
        "re-run the Phase 02 rule catalog and regenerate instead."
    )
    lines.append("")
    lines.append(
        "Per CLAUDE.md §12, every rule below records **rule, finding, severity, "
        "consequence, and handling decision**. No rule here removes a row; each "
        "handling decision either flags-and-keeps or names an explicit, inspectable "
        "quarantine location, applied in Phase 03's staging layer (this phase only "
        "detects and documents the decision)."
    )
    lines.append("")

    lines.append("## Summary")
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("|---|---|")
    for sev in _SEVERITY_ORDER:
        if by_severity.get(sev, 0):
            lines.append(f"| {sev} | {by_severity[sev]} |")
    lines.append("")

    lines.append("## Rule catalog")
    lines.append("")
    for f in findings:
        lines.append(f"### `{f['rule_id']}` — {f['severity']}")
        lines.append("")
        lines.append(f"**Category:** {f['category']}")
        lines.append("")
        lines.append(f"**Rule:** {f['description']}")
        lines.append("")
        lines.append("**Finding:**")
        lines.append("")
        for key, value in f["metrics"].items():
            lines.append(f"- `{key}`: {_fmt(value)}")
        lines.append("")
        lines.append(f"**Consequence:** {f['consequence']}")
        lines.append("")
        lines.append(f"**Handling decision:** {f['handling_decision']}")
        lines.append("")

    return "\n".join(lines)


def generate_and_write(findings_path: Path, out_path: Path, dataset_display_name: str) -> Path:
    findings = json.loads(findings_path.read_text(encoding="utf-8"))
    content = render_dq_report(findings, dataset_display_name)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    return out_path


def _main() -> None:
    from demandflow.config import load_config

    cfg = load_config()
    findings_path = cfg.paths.reports_dir / "phase02" / "dq_findings.json"
    if not findings_path.exists():
        raise FileNotFoundError(
            f"Expected {findings_path} to exist. Run demandflow.quality.rules first."
        )
    out_path = Path("docs") / "data_quality" / "dq_report.md"
    generate_and_write(findings_path, out_path, cfg.dataset.display_name)
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    _main()
