"""Render docs/monitoring.md from a Phase 10 monitoring snapshot.

Same principle as every previous phase's report generator: built entirely
from reports/phase10/monitoring_snapshot.json, never hand-typed -- the
overall status and every signal's status/reason are copied from whatever
the real thresholds found on that run.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

SIGNAL_TITLES = {
    "forecast_accuracy": "Forecast accuracy",
    "forecast_deterioration": "Forecast deterioration",
    "data_quality": "Data quality",
    "anomalies": "Anomalies",
}

def _badge(status: str) -> str:
    return f"**{status}**"


def _signal_section(signal: dict[str, Any]) -> list[str]:
    title = SIGNAL_TITLES.get(signal["signal"], signal["signal"])
    lines = [f"## {title} — {_badge(signal['status'])}", ""]
    lines.append(signal["reason"])
    lines.append("")

    extra_keys = [
        k for k in signal
        if k not in {"signal", "status", "reason", "recent_anomalies", "driving_rules", "severity_counts"}
    ]
    if extra_keys:
        lines.append("| Field | Value |\n|---|---|")
        for k in extra_keys:
            lines.append(f"| {k} | {signal[k]} |")
        lines.append("")

    if signal.get("severity_counts"):
        lines.append("Severity counts: " + ", ".join(f"{k}={v}" for k, v in signal["severity_counts"].items()))
        lines.append("")
    if signal.get("driving_rules"):
        lines.append("Driving rule(s): " + ", ".join(signal["driving_rules"]))
        lines.append("")
    if signal.get("recent_anomalies"):
        lines.append("| Date | Total units | z-score |\n|---|---|---|")
        for a in signal["recent_anomalies"]:
            lines.append(f"| {a['date']} | {a['total_unit_sales']} | {a['z_score']:.2f} |")
        lines.append("")
    return lines


def render_monitoring_report(summary: dict[str, Any], dataset_display_name: str) -> str:
    generated_at = datetime.now(timezone.utc).isoformat()
    lines: list[str] = []

    lines.append(f"# Monitoring — {dataset_display_name}")
    lines.append("")
    lines.append(
        "> Generated by `demandflow.reporting.generate_monitoring_report` from "
        f"`reports/phase10/monitoring_snapshot.json` at `{generated_at}`. Do not hand-edit — "
        "re-run the Phase 10 monitoring check and regenerate instead."
    )
    lines.append("")

    lines.append("## Scope")
    lines.append("")
    lines.append(
        "This is one point-in-time health check across four signals the JD names or implies: "
        "**forecast accuracy**, **forecast deterioration**, **data quality**, and **anomalies**. "
        "Each signal is classified OK / WARN / BREACH / UNKNOWN against an explicit, documented "
        "threshold (`demandflow.monitoring.signals`) — turning a number Phases 02-06 already "
        "compute into an automated verdict is this phase's entire job. This phase does not "
        "persist a history of snapshots or send a notification anywhere — logging results over "
        "time and raising an actual alert is Phase 11's job (Alerts / Trackers), a separate item "
        "on the project's own phase list."
    )
    lines.append("")

    lines.append(f"## Overall status: {_badge(summary.get('overall_status', 'UNKNOWN'))}")
    lines.append("")
    lines.append(f"Champion model at check time: **{summary.get('champion_model', 'n/a')}**.")
    lines.append("")
    lines.append("| Signal | Status |\n|---|---|")
    for s in summary.get("signals", []):
        lines.append(f"| {SIGNAL_TITLES.get(s['signal'], s['signal'])} | {_badge(s['status'])} |")
    lines.append("")

    for s in summary.get("signals", []):
        lines.extend(_signal_section(s))

    lines.append("## Limitations")
    lines.append("")
    lines.append(
        "- Validated end-to-end only against the small committed synthetic fixture "
        "(tests/fixtures/favorita_sample/) in this sandbox, which has no Kaggle network access "
        "— not against the real Favorita dataset. In particular, the data-quality signal's "
        "severities here reflect a 52-row fixture (e.g. 1 duplicate row reads as a whole "
        "percentage point); the same absolute counts would be a rounding error at real scale, "
        "and the real dataset may surface entirely different rule severities.\n"
        "- Thresholds (WAPE WARN/BREACH lines, deterioration ratio, anomaly look-back window) "
        "are heuristic, documented `[DECISION]`s in `demandflow.monitoring.signals`, not JD "
        "figures.\n"
        "- The deterioration signal compares the most recent as-of date against a pool of "
        "earlier as-of dates; with as few as-of dates as this project's dev scope produces, an "
        "OK/WARN/BREACH verdict here is far less statistically robust than it would be with a "
        "real, much longer backtest history.\n"
        "- This snapshot is not persisted anywhere — running it again overwrites this file. "
        "Trend-over-multiple-runs tracking is explicitly Phase 11's job."
    )
    lines.append("")

    return "\n".join(lines)


def generate_and_write(summary_path: Path, out_path: Path, dataset_display_name: str) -> Path:
    summary = json.loads(summary_path.read_text(encoding="utf-8"))
    content = render_monitoring_report(summary, dataset_display_name)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    return out_path


def _main() -> None:
    from demandflow.config import load_config

    cfg = load_config()
    summary_path = cfg.paths.reports_dir / "phase10" / "monitoring_snapshot.json"
    if not summary_path.exists():
        raise FileNotFoundError(
            f"Expected {summary_path} to exist. Run demandflow.monitoring.run_monitoring first."
        )
    out_path = Path("docs") / "monitoring.md"
    generate_and_write(summary_path, out_path, cfg.dataset.display_name)
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    _main()
