"""Render docs/forecast_baselines.md from a Phase 05 backtest summary.

Same principle as every previous phase's report generator: built from
reports/phase05/backtest_summary.json (produced by
demandflow.forecasting.run_backtest), never hand-typed.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

MODEL_LABELS = {"naive": "Naive", "seasonal_naive": "Seasonal Naive"}


def _num(value: float | None, digits: int = 3) -> str:
    return "n/a" if value is None else f"{value:,.{digits}f}"


def _metrics_row(model: str, metrics: dict[str, Any]) -> str:
    label = MODEL_LABELS.get(model, model)
    return (
        f"| {label} | {metrics['n']} | {_num(metrics['wape'])} | {_num(metrics['mae'])} | "
        f"{_num(metrics['rmse'])} | {_num(metrics['forecast_bias'])} | "
        f"{_num(metrics['mape'])} ({metrics['included_count']}/{metrics['n']} scored, "
        f"{metrics['excluded_zero_actual_count']} zero-actual excluded) |"
    )


def render_forecast_baselines_report(
    summary: dict[str, Any],
    dataset_display_name: str,
    horizon_days: int,
    season_length_days: int,
    as_of_cadence_days: int,
) -> str:
    generated_at = datetime.now(timezone.utc).isoformat()
    lines: list[str] = []

    lines.append(f"# Forecast Baselines — {dataset_display_name}")
    lines.append("")
    lines.append(
        f"> Generated by `demandflow.reporting.generate_forecast_baselines_report` from "
        f"`reports/phase05/backtest_summary.json` at `{generated_at}`. Do not hand-edit — "
        "re-run the Phase 05 backtest and regenerate instead."
    )
    lines.append("")
    lines.append(
        f"Grain: hub × SKU × day (development scope, ADR 0001 §2.1). "
        f"Horizon: {horizon_days} days. Seasonal Naive period: {season_length_days} days. "
        f"As-of cadence: every {as_of_cadence_days} days. All `[DECISION]`/`[ASSUMPTION]` values "
        "carried from Phase 00's business scenario and Phase 05's own choice of season length "
        "(see docs/phase_reports/phase05.md) — not JD requirements."
    )
    lines.append("")
    lines.append(
        "**Time-aware validation (CLAUDE.md §10):** every forecast at a given as-of date uses "
        "only history up to and including that date; a target date is scored only once it falls "
        "inside its series' own observed active window (Phase 03), never fabricated. No random "
        "train/test split was used."
    )
    lines.append("")

    lines.append("## Overall comparison (all as-of dates)")
    lines.append("")
    lines.append(
        f"As-of dates used: {', '.join(summary.get('as_of_dates_used', []))} "
        f"({summary.get('total_scored_records', 0)} of {summary.get('total_records', 0)} "
        "forecast rows were scorable)"
    )
    lines.append("")
    lines.append(
        "| Model | n | WAPE | MAE | RMSE | Bias | MAPE (excl. zero actuals) |"
        "\n|---|---|---|---|---|---|---|"
    )
    for model, metrics in summary.get("overall_by_model", {}).items():
        lines.append(_metrics_row(model, metrics))
    lines.append("")
    winner = summary.get("lower_wape_model")
    if winner:
        lines.append(
            f"**Lower WAPE: {MODEL_LABELS.get(winner, winner)}.** WAPE is the primary metric here "
            "(not MAPE) because Phase 04's SKU analysis found most development-scope items are "
            "intermittent — MAPE is undefined at zero actuals and excludes a large share of points "
            "(see the exclusion counts above), while WAPE aggregates across zero and nonzero days "
            "without needing to discard any of them."
        )
    lines.append("")

    lines.append("## Final holdout (most recent as-of date)")
    lines.append("")
    holdout = summary.get("final_holdout") or {}
    if holdout:
        lines.append(f"As-of date: `{holdout.get('as_of_date')}` (Phase 00 plan assumption A8)")
        lines.append("")
        lines.append("| Model | n | WAPE | MAE | RMSE | Bias |\n|---|---|---|---|---|---|")
        for model, metrics in holdout.get("by_model", {}).items():
            label = MODEL_LABELS.get(model, model)
            lines.append(
                f"| {label} | {metrics['n']} | {_num(metrics['wape'])} | {_num(metrics['mae'])} | "
                f"{_num(metrics['rmse'])} | {_num(metrics['forecast_bias'])} |"
            )
    else:
        lines.append("No scored as-of date available.")
    lines.append("")

    lines.append("## By horizon step")
    lines.append("")
    lines.append(
        "A coarse breakdown, not the full accuracy-by-segment/horizon framework "
        "(that's Phase 08's job) — just enough to see whether error grows with horizon."
    )
    lines.append("")
    by_horizon = summary.get("by_horizon_step", {})
    horizon_steps = sorted({int(h) for model_data in by_horizon.values() for h in model_data})
    if horizon_steps:
        header = "| Horizon step | " + " | ".join(MODEL_LABELS.get(m, m) + " WAPE" for m in by_horizon) + " |"
        lines.append(header)
        lines.append("|" + "---|" * (len(by_horizon) + 1))
        for h in horizon_steps:
            row = [str(h)]
            for model in by_horizon:
                cell = by_horizon[model].get(str(h)) or by_horizon[model].get(h)
                row.append(_num(cell["wape"]) if cell else "n/a")
            lines.append("| " + " | ".join(row) + " |")
    lines.append("")

    return "\n".join(lines)


def generate_and_write(
    summary_path: Path,
    out_path: Path,
    dataset_display_name: str,
    horizon_days: int,
    season_length_days: int,
    as_of_cadence_days: int,
) -> Path:
    summary = json.loads(summary_path.read_text(encoding="utf-8"))
    content = render_forecast_baselines_report(
        summary, dataset_display_name, horizon_days, season_length_days, as_of_cadence_days
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    return out_path


def _main() -> None:
    from demandflow.config import load_config

    cfg = load_config()
    summary_path = cfg.paths.reports_dir / "phase05" / "backtest_summary.json"
    if not summary_path.exists():
        raise FileNotFoundError(
            f"Expected {summary_path} to exist. Run demandflow.forecasting.run_backtest first."
        )
    out_path = Path("docs") / "forecast_baselines.md"
    generate_and_write(
        summary_path, out_path, cfg.dataset.display_name,
        cfg.forecasting.horizon_days, cfg.forecasting.season_length_days, cfg.forecasting.as_of_cadence_days,
    )
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    _main()
